### ISSUE TITLE
Failure to redeem rewards/yields because of "Exception thrown in contract code." FUNCTION TYPE: Withdraw

### ISSUE THREAD

**Issue by tunga0** [fetchai/mettalex-market-maker#22] opened 2021-03-01 13:12 UTC
![image](https://user-images.githubusercontent.com/50461547/109501610-bb868780-7a8f-11eb-858c-3fd7ff4026a8.png)

FUNCTION TYPE: Withdraw
Parameters:
[
  {
    "type": "uint256"
  },
  {
    "type": "uint256"
  }
]
HEX DATA: 68 BYTES
0x441a3e7000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

ALERT: Transaction Error. Exception thrown in contract code.

**Comment by tunga0** [comment] 2021-03-01 13:30
This error occurs when a user clicks the "CLAIM ANYMTLX REWARDS" button. Steps to reproduce are:

1) Connect Metamask wallet to Binance Smart Chain network in your browser (e.g. Chrome browser on Windows desktop)

2) Open https://amplify-bsc.mettalex.com/ in your web browser, and connect to wallet, select Metamask

3) Make sure to check your BNB balance to ensure you have enough BNB to pay for the transaction fees. The wallet in question has more than 0.5558 BNB, which should be more than enough to pay for any transaction on the Binance Smart Chain.

4) Attempt to claim your rewards by clicking the "CLAIM ANYMTLX REWARDS" button.
![image](https://user-images.githubusercontent.com/50461547/109502001-541d0780-7a90-11eb-8020-fa9d8c89bb77.png)

5) Metamask will pop up and ask you to Reject or Confirm the transaction. If the bug occurs, this is what you'll see in Metamask:
![image](https://user-images.githubusercontent.com/50461547/109503583-5e400580-7a92-11eb-96b4-ab9de4e740b2.png)

Click on "Data" in Metamask so you can see the hex code:
![image](https://user-images.githubusercontent.com/50461547/109502850-71060a80-7a91-11eb-9201-022fd84c9b3d.png)
```
FUNCTION TYPE: Withdraw
Parameters:
[
{
"type": "uint256"
},
{
"type": "uint256"
}
]
HEX DATA: 68 BYTES
0x441a3e7000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

6) The rewards being claimed during this incident are 3.13 anyMTLX, which are worth $24.89. Yet the "AMOUNT + GAS FEE" shown in Metamask is 0.285. That is inaccurate because at the time of writing this, 1 BNB = $255, therefore, given that the rewards being claimed are only worth $24.89 and that the Binance Smart Chain fees don't usually exceed $1 per transaction to date, I'd suggest there is something wrong. But point number 6 is just a side-note for this particular issue which I've reported.

**Comment by tunga0** [comment] 2021-03-01 19:18
### Some debug info from my research shows that the bug (if it is really a bug) might be in the Amplify.sol code.

Below are the details of my analysis:

1) Read the Amplify.sol contract, I couldn't find it in https://github.com/fetchai/mettalex-market-maker/ so I took to bscscan.com, where I found this:
https://bscscan.com/address/0x73ef71e8774dfdd7857bf02c15ac2df122dc8c91#code

2) Click on "Decompile bytecode", you will see the decompiled bytecode of the contract.
 It's interesting to note the "I failed with these" message, which shows the withdraw(uint256 _devAmount, uint256 _submissionAmount) function, which takes two uint256 arguments. That withraw() function matches the signature of the error message which popped up in Metamask when the user  tried to claim thir anyMTLX ewards.
![image](https://user-images.githubusercontent.com/50461547/109545065-42535880-7ac0-11eb-9286-a30f4d2e11ad.png)

https://bscscan.com/bytecode-decompiler?a=0x73ef71e8774dfdd7857bf02c15ac2df122dc8c91

3) Open the contract code in https://bscscan.com/address/0x73ef71e8774dfdd7857bf02c15ac2df122dc8c91 and inspect it. Look for a withdraw function which takes two uint256 arguments. You will find this function, which resides in "Amplify.sol".

```
    // Withdraw LP tokens from Amplify.
    function withdraw(uint256 _pid, uint256 _amount) public whenNotPaused {
        PoolInfo storage pool = poolInfo[_pid];
        UserInfo storage user = userInfo[_pid][msg.sender];
        require(user.amount >= _amount, "withdraw: not good");
        updatePool(_pid);
        uint256 pending =
            user.amount.mul(pool.accMTLXPerShare).div(1e12).sub(
                user.rewardDebt
            );
        if (pending > 0) {
            safeMTLXTransfer(msg.sender, pending);
        }
        if (_amount > 0) {
            user.amount = user.amount.sub(_amount);
            uint256 exitFee = _amount.mul(exitFeeFactor).div(100).div(1e18);
            pool.lpToken.safeTransfer(
                address(msg.sender),
                _amount.sub(exitFee)
            );
            pool.lpToken.safeTransfer(devaddr, exitFee);
        }
        user.rewardDebt = user.amount.mul(pool.accMTLXPerShare).div(1e12);
        emit Withdraw(msg.sender, _pid, _amount);
    }
```

4) Search for Hex data 0x441a3e70, which was returned as part of the error message by Metamask when the user tried to claim their anyMTLX rewards. That hash appears in the compilation of the contract but I'm not certain if this means something as I am not a Solidity expert (yet) :).
![image](https://user-images.githubusercontent.com/50461547/109546333-f2759100-7ac1-11eb-8dc1-379a5e0d3e7e.png)

**Comment by mattmcd** [comment] 2021-03-02 15:41
Thanks for a detailed reproduction steps and investigation.  It turns out the root cause was an operational issue in that we needed to top up the Amplify contract with more MTLX.  There doesn't appear to be any issue with the actual code so closing this issue.

**Closed as completed by mattmcd** 2021-03-02 15:41 UTC

**Comment by tunga0** [comment] 2021-03-02 17:44
Thanks @mattmcd !

**Comment by tunga0** [comment] 2021-03-24 20:54
Hi @mattmcd, it looks like the Amplify contract needs to be topped up with more MTLX again. There are other issues which I raised as well last week but they are not related to this issue.

**Comment by tunga0** [comment] 2021-04-19 12:09
Hi @mattmcd, @MehulG Please top up the Amplify contact, users have been unable to withdraw from Mettalex for 24 hours now.

![image](https://user-images.githubusercontent.com/50461547/115234037-83570900-a110-11eb-830c-0db4845839e9.png)

**Comment by mattmcd** [comment] 2021-04-21 08:07
Thanks @tunga0 this has been addressed and the BSC Amplify contract topped up.  Please note that the Amplify contracts are in a separate repo to this one and it is better to report any issues encountered with Amplify on the Mettalex Telegram channel.
